spring:
  datasource:
    url: jdbc:postgresql://sa-coding-hackathon.cluster-chur8opkdp9u.us-east-1.rds.amazonaws.com:5432/SA_CODING
    username: legendofjava
    password: ${POSTGRES_SECRET}
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true
